### ISSUE TITLE
License Inquiry

### ISSUE THREAD

**Issue by knackstedt** [pop-os/icon-theme#133]
I'm making an open source web filemanager component, and I'd like to use the Pop!_os file icons for it. I know the general license is CC-By-SA 4.0, but I'm not certain if that means I need to add some attribution only to my source code, or add attribution into the web component somewhere.

Would someone be kind enough to clarify what I should do?
I'd really like to have something in writing, because I'm getting mixed answers from some sources

**Comment by jacobgkau** [comment]
Thanks for reaching out. Looking at some references, this topic isn't discussed much, and I do see some conflicting info like you said.

It sounds like your project has a GUI since it's using an icon theme. If the GUI includes an "about" page (e.g. the common Help -> About dialog), then that would be an ideal location to provide attribution. However, if it doesn't have that kind of page or any other location where you'd include your own copyright or authorship notice (e.g. if it's only a library or something), then I believe just providing the attribution in your project's source code and/or README file would satisfy the terms of the license. This would be "reasonable to the means, medium, and context of how one shares a work" as stated in the license text.

**Comment by knackstedt** [comment]
Thanks, I'm writing it as an Angular Web component, so it doesn't really have an about page, though I could add an info button that brings up a dialog.
I believe they would, but just to confirm -- Would web apps that use my component also need to follow the same attribution requirements?

**Comment by jacobgkau** [comment]
> I believe they would, but just to confirm -- Would web apps that use my component also need to follow the same attribution requirements?

I agree that the answer is yes. The attribution requirement wouldn't go away because of an intermediary step/usage.

Ideally, however you implement it would generally be inherited by people using your project/code automatically.

**Comment by knackstedt** [comment]
Awesome, thank you so much for the additional confirmation :)
