### ISSUE TITLE
Installation failed [Makefile Error]

### ISSUE THREAD

**Issue by ArvindNair001** [pop-os/icon-theme#30]
**Reporter info**

 * Distribution - Fedora 27 
 * Gtk+ 3.0 version - 3.22.26-2
 * Desktop environment - GNOME 3.26

**Steps to reproduce (if you knew)**
sudo make install
sudo make post-install
![screenshot from 2018-04-23 19-45-19](https://user-images.githubusercontent.com/21971773/39132827-62261f1a-4730-11e8-94b1-5a957cbeed71.png)

**Comment by isantop** [comment]
I don't think that actually affects the installation of the theme. Can you select the icons in Tweak tool?

**Comment by Tids** [comment]
Not all Icons where loaded. For Example, corebird is back to its papirus icon, the same with gnome-web. Both of them also dont have to colorpalett of pop, but the default papirus one

![gnome-shell-screenshot-ux0ihz](https://user-images.githubusercontent.com/18744080/39150601-2a8c3fea-4743-11e8-80f3-8ea210de7f73.png)

**Comment by VanackSabbadium** [comment]
Hi, i've got the same issue and i can't select the icons in my tweak tool.

Distribution: Ubuntu 18.04
Desktop environment: XFCE 4.12

Thanks for your help.

**Comment by drakkan** [comment]
Hi, the same issue happen on archlinux with gnome 3.28

**Comment by Lt-Mayonesa** [comment]
Hi! the same happened to me (Linux Mint 19.1, Cinnamon 4.0)

This happens due to this file [./Papirus/24x24/places/user-yellow-desktop (copy).svg](https://github.com/pop-os/icon-theme/blob/master/Papirus/24x24/places/user-yellow-desktop%20(copy).svg).

It seems that `gtk-update-icon-cache` does not support spaces in file names.

By removing it and running the command again it worked like a charm.
